export const metadata = {
  title: "Next Template",
  description: "Generated by setup"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
